apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: touca-ebs
  namespace: {{ .Release.Name }}-touca
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources: 
    requests:
      storage: 4Gi